projects:
  tennisreact-staging:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        region: us-west-1
        apiId: ctfb4fnlsbgdvmio6vrotgipk4
        maxDepth: 2
extensions:
  amplify:
    version: 3
