const bracket_data = {
  "rounds": [
    {
      "round_of": 64,
      "round_of_text": "Round of 64",
      "matches": [
        {
          "id": "a85c6707-30b8-4c6f-81ae-459538741f71",
          "match_number": "64.1",
          "match_id": null,
          "round_of_text": "Round of 64",
          "round_of": 64,
          "player1": {
            "id": "a0ee264b-9486-49dc-908a-ee9b7d0485aa",
            "name": "Jonas Persson"
          },
          "seed1": null,
          "player2": {
            "id": "433028e7-a9bc-48ea-83c5-4deba4626a53",
            "name": "Player 23"
          },
          "seed2": null,
          "participant1_id": "9685dbe7-3712-4781-bb18-5fb41eec0b72",
          "participant1_name": "A bit longer name Player 17",
          "participant2_id": "6b8631ba-6ebd-4fd1-96f5-99cf0f7d258c",
          "participant2_name": "Player 23",
          "score": "6-2, 4-6, 6-3",
          "winner_id": "9685dbe7-3712-4781-bb18-5fb41eec0b72",
          "next_match_id": null,
          "match_iteration": 1
        },
        {
          "id": "d4276342-9887-4b2b-99d6-2eaf2f1229ec",
          "match_number": "64.2",
          "match_id": null,
          "round_of_text": "Round of 64",
          "round_of": 64,
          "player1": null,
          "seed1": null,
          "player2": null,
          "seed2": null,
          "participant1_id": null,
          "participant1_name": "TBD",
          "participant2_id": null,
          "participant2_name": "TBD",
          "score": null,
          "winner_id": null,
          "next_match_id": null,
          "match_iteration": 2
        },
        {
          "id": "26513c80-4b5a-4007-910e-77aca106054e",
          "match_number": "64.3",
          "match_id": null,
          "round_of_text": "Round of 64",
          "round_of": 64,
          "player1": null,
          "seed1": null,
          "player2": null,
          "seed2": null,
          "participant1_id": null,
          "participant1_name": "TBD",
          "participant2_id": null,
          "participant2_name": "TBD",
          "score": null,
          "winner_id": null,
          "next_match_id": null,
          "match_iteration": 3
        },
        {
          "id": "92fedda5-5bf5-4ef7-bf0e-e76160ba81de",
          "match_number": "64.4",
          "match_id": null,
          "round_of_text": "Round of 64",
          "round_of": 64,
          "player1": null,
          "seed1": null,
          "player2": null,
          "seed2": null,
          "participant1_id": null,
          "participant1_name": "TBD",
          "participant2_id": null,
          "participant2_name": "TBD",
          "score": null,
          "winner_id": null,
          "next_match_id": null,
          "match_iteration": 4
        },
        {
          "id": "f00c1d29-cfec-4fd8-92bf-1c294224071e",
          "match_number": "64.5",
          "match_id": null,
          "round_of_text": "Round of 64",
          "round_of": 64,
          "player1": null,
          "seed1": null,
          "player2": null,
          "seed2": null,
          "participant1_id": null,
          "participant1_name": "TBD",
          "participant2_id": null,
          "participant2_name": "TBD",
          "score": null,
          "winner_id": null,
          "next_match_id": null,
          "match_iteration": 5
        },
        {
          "id": "2641d91e-2708-4de2-a118-798153a5fbb5",
          "match_number": "64.6",
          "match_id": null,
          "round_of_text": "Round of 64",
          "round_of": 64,
          "player1": null,
          "seed1": null,
          "player2": null,
          "seed2": null,
          "participant1_id": null,
          "participant1_name": "TBD",
          "participant2_id": null,
          "participant2_name": "TBD",
          "score": null,
          "winner_id": null,
          "next_match_id": null,
          "match_iteration": 6
        },
        {
          "id": "b719bdfc-5d61-4e59-bb61-d726524c24fe",
          "match_number": "64.7",
          "match_id": null,
          "round_of_text": "Round of 64",
          "round_of": 64,
          "player1": null,
          "seed1": null,
          "player2": null,
          "seed2": null,
          "participant1_id": null,
          "participant1_name": "TBD",
          "participant2_id": null,
          "participant2_name": "TBD",
          "score": null,
          "winner_id": null,
          "next_match_id": null,
          "match_iteration": 7
        },
        {
          "id": "6c98b04c-d2b7-474d-9364-3c295f0021a6",
          "match_number": "64.8",
          "match_id": null,
          "round_of_text": "Round of 64",
          "round_of": 64,
          "player1": null,
          "seed1": null,
          "player2": null,
          "seed2": null,
          "participant1_id": null,
          "participant1_name": "TBD",
          "participant2_id": null,
          "participant2_name": "TBD",
          "score": null,
          "winner_id": null,
          "next_match_id": null,
          "match_iteration": 8
        },
        {
          "id": "d33e2ed7-90f2-403e-b3d6-24837fd0d956",
          "match_number": "64.9",
          "match_id": null,
          "round_of_text": "Round of 64",
          "round_of": 64,
          "player1": {
            "id": "b9f3a560-52f3-4ee0-94f3-660e9a836cbd",
            "name": "Player 37"
          },
          "seed1": null,
          "player2": {
            "id": "eb4894c2-af62-4902-85b9-9088cb75a7b3",
            "name": "Player 13"
          },
          "seed2": null,
          "participant1_id": "861b13f7-e590-49a1-9743-281e44228877",
          "participant1_name": "Player 37",
          "participant2_id": "18d80cd9-5a5f-48b2-85c7-1cabceda3904",
          "participant2_name": "Player 13",
          "score": null,
          "winner_id": null,
          "next_match_id": null,
          "match_iteration": 9
        },
        {
          "id": "6a6d066f-7bea-47d2-b52d-d7eabcbdaa5f",
          "match_number": "64.10",
          "match_id": null,
          "round_of_text": "Round of 64",
          "round_of": 64,
          "player1": null,
          "seed1": null,
          "player2": null,
          "seed2": null,
          "participant1_id": null,
          "participant1_name": "TBD",
          "participant2_id": null,
          "participant2_name": "TBD",
          "score": null,
          "winner_id": null,
          "next_match_id": null,
          "match_iteration": 10
        },
        {
          "id": "1f279105-b956-40cc-ac0b-b2950c7f9e93",
          "match_number": "64.11",
          "match_id": null,
          "round_of_text": "Round of 64",
          "round_of": 64,
          "player1": null,
          "seed1": null,
          "player2": null,
          "seed2": null,
          "participant1_id": null,
          "participant1_name": "TBD",
          "participant2_id": null,
          "participant2_name": "TBD",
          "score": null,
          "winner_id": null,
          "next_match_id": null,
          "match_iteration": 11
        },
        {
          "id": "fbab3063-4de7-4766-a39a-a89e8294e541",
          "match_number": "64.12",
          "match_id": null,
          "round_of_text": "Round of 64",
          "round_of": 64,
          "player1": null,
          "seed1": null,
          "player2": null,
          "seed2": null,
          "participant1_id": null,
          "participant1_name": "TBD",
          "participant2_id": null,
          "participant2_name": "TBD",
          "score": null,
          "winner_id": null,
          "next_match_id": null,
          "match_iteration": 12
        },
        {
          "id": "7a089ac3-36cb-4ca6-8066-5c138535b068",
          "match_number": "64.13",
          "match_id": null,
          "round_of_text": "Round of 64",
          "round_of": 64,
          "player1": null,
          "seed1": null,
          "player2": null,
          "seed2": null,
          "participant1_id": null,
          "participant1_name": "TBD",
          "participant2_id": null,
          "participant2_name": "TBD",
          "score": null,
          "winner_id": null,
          "next_match_id": null,
          "match_iteration": 13
        },
        {
          "id": "d3affe38-1987-4013-a0b4-e25cee27b1b6",
          "match_number": "64.14",
          "match_id": null,
          "round_of_text": "Round of 64",
          "round_of": 64,
          "player1": null,
          "seed1": null,
          "player2": null,
          "seed2": null,
          "participant1_id": null,
          "participant1_name": "TBD",
          "participant2_id": null,
          "participant2_name": "TBD",
          "score": null,
          "winner_id": null,
          "next_match_id": null,
          "match_iteration": 14
        },
        {
          "id": "df8614e1-fd58-43c4-850f-882e78569a5b",
          "match_number": "64.15",
          "match_id": null,
          "round_of_text": "Round of 64",
          "round_of": 64,
          "player1": null,
          "seed1": null,
          "player2": null,
          "seed2": null,
          "participant1_id": null,
          "participant1_name": "TBD",
          "participant2_id": null,
          "participant2_name": "TBD",
          "score": null,
          "winner_id": null,
          "next_match_id": null,
          "match_iteration": 15
        },
        {
          "id": "306e7caa-932a-467b-b63f-87734244cae3",
          "match_number": "64.16",
          "match_id": null,
          "round_of_text": "Round of 64",
          "round_of": 64,
          "player1": {
            "id": "880e816d-984a-4db6-bf37-7f8b41998b68",
            "name": "Player 34"
          },
          "seed1": null,
          "player2": {
            "id": "aeb018fc-129f-45f3-b6ec-dcdcb062395c",
            "name": "Player 31"
          },
          "seed2": null,
          "participant1_id": "3590f3a4-ba54-47fd-8537-efec29e8243d",
          "participant1_name": "Player 34",
          "participant2_id": "6bc6cf48-bf67-4f50-81ed-aab24af58c74",
          "participant2_name": "Player 31",
          "score": null,
          "winner_id": null,
          "next_match_id": null,
          "match_iteration": 16
        },
        {
          "id": "ab56bce2-0f55-4af4-9ac2-ad3dd1c9db47",
          "match_number": "64.17",
          "match_id": null,
          "round_of_text": "Round of 64",
          "round_of": 64,
          "player1": {
            "id": "45560c6a-becc-445b-901f-2cc4739ad271",
            "name": "Player 16"
          },
          "seed1": null,
          "player2": {
            "id": "bbc96305-6a40-4ad5-9af4-897526c8e7cd",
            "name": "Player 30"
          },
          "seed2": null,
          "participant1_id": "506f11d6-70b3-4575-b4d4-c9e7a030e3b7",
          "participant1_name": "Player 16",
          "participant2_id": "80276176-d3da-4923-8bb6-f2ff7e058bb1",
          "participant2_name": "Player 30",
          "score": null,
          "winner_id": null,
          "next_match_id": null,
          "match_iteration": 17
        },
        {
          "id": "5a4d22eb-dbcd-40c4-bdb5-31eaecb93c55",
          "match_number": "64.18",
          "match_id": null,
          "round_of_text": "Round of 64",
          "round_of": 64,
          "player1": null,
          "seed1": null,
          "player2": null,
          "seed2": null,
          "participant1_id": null,
          "participant1_name": "TBD",
          "participant2_id": null,
          "participant2_name": "TBD",
          "score": null,
          "winner_id": null,
          "next_match_id": null,
          "match_iteration": 18
        },
        {
          "id": "cfd82476-83c9-4a11-abfa-1870149ab043",
          "match_number": "64.19",
          "match_id": null,
          "round_of_text": "Round of 64",
          "round_of": 64,
          "player1": null,
          "seed1": null,
          "player2": null,
          "seed2": null,
          "participant1_id": null,
          "participant1_name": "TBD",
          "participant2_id": null,
          "participant2_name": "TBD",
          "score": null,
          "winner_id": null,
          "next_match_id": null,
          "match_iteration": 19
        },
        {
          "id": "3aae34d5-6ed2-4cb2-9d8f-ff3ff92e278a",
          "match_number": "64.20",
          "match_id": null,
          "round_of_text": "Round of 64",
          "round_of": 64,
          "player1": null,
          "seed1": null,
          "player2": null,
          "seed2": null,
          "participant1_id": null,
          "participant1_name": "TBD",
          "participant2_id": null,
          "participant2_name": "TBD",
          "score": null,
          "winner_id": null,
          "next_match_id": null,
          "match_iteration": 20
        },
        {
          "id": "dffb3967-d91e-44ae-9ff1-5d4924dd12e5",
          "match_number": "64.21",
          "match_id": null,
          "round_of_text": "Round of 64",
          "round_of": 64,
          "player1": null,
          "seed1": null,
          "player2": null,
          "seed2": null,
          "participant1_id": null,
          "participant1_name": "TBD",
          "participant2_id": null,
          "participant2_name": "TBD",
          "score": null,
          "winner_id": null,
          "next_match_id": null,
          "match_iteration": 21
        },
        {
          "id": "471ec5fb-cc07-44f4-9aba-ea7e75dfa2c6",
          "match_number": "64.22",
          "match_id": null,
          "round_of_text": "Round of 64",
          "round_of": 64,
          "player1": null,
          "seed1": null,
          "player2": null,
          "seed2": null,
          "participant1_id": null,
          "participant1_name": "TBD",
          "participant2_id": null,
          "participant2_name": "TBD",
          "score": null,
          "winner_id": null,
          "next_match_id": null,
          "match_iteration": 22
        },
        {
          "id": "e35aada5-cd00-4c4a-8987-4922d411771e",
          "match_number": "64.23",
          "match_id": null,
          "round_of_text": "Round of 64",
          "round_of": 64,
          "player1": null,
          "seed1": null,
          "player2": null,
          "seed2": null,
          "participant1_id": null,
          "participant1_name": "TBD",
          "participant2_id": null,
          "participant2_name": "TBD",
          "score": null,
          "winner_id": null,
          "next_match_id": null,
          "match_iteration": 23
        },
        {
          "id": "33af1040-3099-4563-b0d4-72cfea96bca6",
          "match_number": "64.24",
          "match_id": null,
          "round_of_text": "Round of 64",
          "round_of": 64,
          "player1": null,
          "seed1": null,
          "player2": null,
          "seed2": null,
          "participant1_id": null,
          "participant1_name": "TBD",
          "participant2_id": null,
          "participant2_name": "TBD",
          "score": null,
          "winner_id": null,
          "next_match_id": null,
          "match_iteration": 24
        },
        {
          "id": "8730f61b-bc40-42c3-a03d-49bd245b2872",
          "match_number": "64.25",
          "match_id": null,
          "round_of_text": "Round of 64",
          "round_of": 64,
          "player1": null,
          "seed1": null,
          "player2": null,
          "seed2": null,
          "participant1_id": null,
          "participant1_name": "TBD",
          "participant2_id": null,
          "participant2_name": "TBD",
          "score": null,
          "winner_id": null,
          "next_match_id": null,
          "match_iteration": 25
        },
        {
          "id": "698c50b5-2f77-4422-a0eb-40454f40010b",
          "match_number": "64.26",
          "match_id": null,
          "round_of_text": "Round of 64",
          "round_of": 64,
          "player1": null,
          "seed1": null,
          "player2": null,
          "seed2": null,
          "participant1_id": null,
          "participant1_name": "TBD",
          "participant2_id": null,
          "participant2_name": "TBD",
          "score": null,
          "winner_id": null,
          "next_match_id": null,
          "match_iteration": 26
        },
        {
          "id": "bc2572ed-4545-4f45-8388-2783a2c09bc0",
          "match_number": "64.27",
          "match_id": null,
          "round_of_text": "Round of 64",
          "round_of": 64,
          "player1": null,
          "seed1": null,
          "player2": null,
          "seed2": null,
          "participant1_id": null,
          "participant1_name": "TBD",
          "participant2_id": null,
          "participant2_name": "TBD",
          "score": null,
          "winner_id": null,
          "next_match_id": null,
          "match_iteration": 27
        },
        {
          "id": "e3acaad9-1378-4a7d-ae72-d22e64dc80c9",
          "match_number": "64.28",
          "match_id": null,
          "round_of_text": "Round of 64",
          "round_of": 64,
          "player1": null,
          "seed1": null,
          "player2": null,
          "seed2": null,
          "participant1_id": null,
          "participant1_name": "TBD",
          "participant2_id": null,
          "participant2_name": "TBD",
          "score": null,
          "winner_id": null,
          "next_match_id": null,
          "match_iteration": 28
        },
        {
          "id": "316f6f26-5243-4aea-9d6c-76d1174d58e8",
          "match_number": "64.29",
          "match_id": null,
          "round_of_text": "Round of 64",
          "round_of": 64,
          "player1": null,
          "seed1": null,
          "player2": null,
          "seed2": null,
          "participant1_id": null,
          "participant1_name": "TBD",
          "participant2_id": null,
          "participant2_name": "TBD",
          "score": null,
          "winner_id": null,
          "next_match_id": null,
          "match_iteration": 29
        },
        {
          "id": "cf288a57-d7d6-416a-a9a8-cb2182d5a18f",
          "match_number": "64.30",
          "match_id": null,
          "round_of_text": "Round of 64",
          "round_of": 64,
          "player1": null,
          "seed1": null,
          "player2": null,
          "seed2": null,
          "participant1_id": null,
          "participant1_name": "TBD",
          "participant2_id": null,
          "participant2_name": "TBD",
          "score": null,
          "winner_id": null,
          "next_match_id": null,
          "match_iteration": 30
        },
        {
          "id": "052712e4-a236-498a-8ac7-ee2140c487b5",
          "match_number": "64.31",
          "match_id": null,
          "round_of_text": "Round of 64",
          "round_of": 64,
          "player1": null,
          "seed1": null,
          "player2": null,
          "seed2": null,
          "participant1_id": null,
          "participant1_name": "TBD",
          "participant2_id": null,
          "participant2_name": "TBD",
          "score": null,
          "winner_id": null,
          "next_match_id": null,
          "match_iteration": 31
        },
        {
          "id": "e5b20cdb-7e60-4274-8f2c-d525b0679182",
          "match_number": "64.32",
          "match_id": null,
          "round_of_text": "Round of 64",
          "round_of": 64,
          "player1": {
            "id": "a520b024-24a2-400d-b91e-3aa2d2c6fac1",
            "name": "Player 35"
          },
          "seed1": null,
          "player2": {
            "id": "e2d7de9e-24ba-496e-beba-d5e41cffdf4f",
            "name": "Player 26"
          },
          "seed2": null,
          "participant1_id": "a8f1995e-1297-4708-8946-74391c8fcd13",
          "participant1_name": "Player 35",
          "participant2_id": "8afb4f3f-b5d6-4542-8c22-37ef61f7ec69",
          "participant2_name": "Player 26",
          "score": null,
          "winner_id": null,
          "next_match_id": null,
          "match_iteration": 32
        }
      ]
    },
    {
      "round_of": 32,
      "round_of_text": "Round of 32",
      "matches": [
        {
          "id": "d24578bc-d305-4eb0-825e-bd5a0d59155d",
          "match_number": "32.1",
          "match_id": null,
          "round_of_text": "Round of 32",
          "round_of": 32,
          "player1": {
            "id": "52f67c38-7140-4441-89c0-e4c32fc14532",
            "name": "Player 1"
          },
          "seed1": 1,
          "player2": null,
          "seed2": null,
          "participant1_id": "5e2befe2-2dee-47e3-92b2-a5ccb588e9b7",
          "participant1_name": "Player 1",
          "participant2_id": null,
          "participant2_name": "TBD",
          "score": null,
          "winner_id": null,
          "next_match_id": null,
          "match_iteration": 33
        },
        {
          "id": "0d7d1c50-3184-452b-8f8d-95ec0baf1058",
          "match_number": "32.2",
          "match_id": null,
          "round_of_text": "Round of 32",
          "round_of": 32,
          "player1": {
            "id": "3254002a-dd03-42e3-ad28-387ddf1be46b",
            "name": "Player 29"
          },
          "seed1": null,
          "player2": {
            "id": "0578199e-0d60-4da6-8cd1-58a8fac6594a",
            "name": "Player 15"
          },
          "seed2": null,
          "participant1_id": "ea485451-6186-4c30-abe5-5c955b751777",
          "participant1_name": "Player 29",
          "participant2_id": "0f40332b-d038-4853-a00e-99a7a6217f88",
          "participant2_name": "Player 15",
          "score": null,
          "winner_id": null,
          "next_match_id": null,
          "match_iteration": 34
        },
        {
          "id": "0685c63a-48d1-4e9d-bac0-7b106651fd99",
          "match_number": "32.2",
          "match_id": null,
          "round_of_text": "Round of 32",
          "round_of": 32,
          "player1": {
            "id": "061cf7ad-4d9d-4a74-b9d0-bfd07b483c40",
            "name": "Player 18"
          },
          "seed1": null,
          "player2": {
            "id": "773b98ad-3bc8-4b63-87c0-c0c62b108eb1",
            "name": "Player 11"
          },
          "seed2": null,
          "participant1_id": "5bff9fab-ec7f-46ad-9230-924dc108514b",
          "participant1_name": "Player 18",
          "participant2_id": "0ae51920-64d5-491b-85f6-2ebd8fbf7ae3",
          "participant2_name": "Player 11",
          "score": null,
          "winner_id": null,
          "next_match_id": null,
          "match_iteration": 35
        },
        {
          "id": "e7e8850a-4d0f-443e-a9f3-5d946b6e6e4d",
          "match_number": "32.3",
          "match_id": null,
          "round_of_text": "Round of 32",
          "round_of": 32,
          "player1": {
            "id": "d8112fe5-d400-4c0d-89d6-a105fc7c691f",
            "name": "Player 9"
          },
          "seed1": 9,
          "player2": {
            "id": "15974627-dede-46e8-8100-bcf2c46293b6",
            "name": "Player 8"
          },
          "seed2": 8,
          "participant1_id": "cfc82a12-2090-4360-b207-0d600628e06b",
          "participant1_name": "Player 9",
          "participant2_id": "49433bbc-9290-4724-bcf2-9c41516f68ab",
          "participant2_name": "Player 8",
          "score": null,
          "winner_id": null,
          "next_match_id": null,
          "match_iteration": 36
        },
        {
          "id": "4e2481e5-eebc-4a3f-9341-4e311c2c4ade",
          "match_number": "32.5",
          "match_id": null,
          "round_of_text": "Round of 32",
          "round_of": 32,
          "player1": {
            "id": "fde4a686-e95f-45b2-b041-c94af43628cc",
            "name": "Player 5"
          },
          "seed1": 5,
          "player2": null,
          "seed2": null,
          "participant1_id": "9be21357-a13b-4736-8cb1-55d0ca7635f1",
          "participant1_name": "Player 5",
          "participant2_id": null,
          "participant2_name": "TBD",
          "score": null,
          "winner_id": null,
          "next_match_id": null,
          "match_iteration": 37
        },
        {
          "id": "77bb5e1d-1d4c-42d0-965f-59758b0b2814",
          "match_number": "32.6",
          "match_id": null,
          "round_of_text": "Round of 32",
          "round_of": 32,
          "player1": {
            "id": "7b010a01-11a7-4a3a-8e99-58e9ce700bfa",
            "name": "Player 19"
          },
          "seed1": null,
          "player2": {
            "id": "ba055901-6b3d-4b3e-95ab-5b8be790c6d4",
            "name": "Player 25"
          },
          "seed2": null,
          "participant1_id": "36e73cc9-3200-4e0d-96e0-9993db1a55a9",
          "participant1_name": "Player 19",
          "participant2_id": "8c022fde-e407-4905-b016-5ef257ed0538",
          "participant2_name": "Player 25",
          "score": null,
          "winner_id": null,
          "next_match_id": null,
          "match_iteration": 38
        },
        {
          "id": "60169a17-8f7f-477f-9cb1-f63c8df03e44",
          "match_number": "32.7",
          "match_id": null,
          "round_of_text": "Round of 32",
          "round_of": 32,
          "player1": {
            "id": "2b2747b1-424e-4d40-b277-a0df6ec41cbd",
            "name": "Player 22"
          },
          "seed1": null,
          "player2": {
            "id": "e2a85a95-3a90-4920-8fcc-2f0cd942afd5",
            "name": "Player 12"
          },
          "seed2": null,
          "participant1_id": "22608a30-ac95-43cf-bc0a-06dc8fbce0f2",
          "participant1_name": "Player 22",
          "participant2_id": "a5e4cf9b-b232-43b1-b97a-63212c1adc1b",
          "participant2_name": "Player 12",
          "score": null,
          "winner_id": null,
          "next_match_id": null,
          "match_iteration": 39
        },
        {
          "id": "6a313c8c-ca53-41e8-9eb2-e6367fc40c9f",
          "match_number": "32.8",
          "match_id": null,
          "round_of_text": "Round of 32",
          "round_of": 32,
          "player1": {
            "id": "cc0bf141-bda8-4b85-9e0f-e7bf8a22b11e",
            "name": "Player 4"
          },
          "seed1": 4,
          "player2": null,
          "seed2": null,
          "participant1_id": "7e109c0c-079b-4000-a74c-f202f8cf5865",
          "participant1_name": "Player 4",
          "participant2_id": null,
          "participant2_name": "TBD",
          "score": null,
          "winner_id": null,
          "next_match_id": null,
          "match_iteration": 40
        },
        {
          "id": "b40f4eef-486b-4c22-8fcb-bd157a81397a",
          "match_number": "32.9",
          "match_id": null,
          "round_of_text": "Round of 32",
          "round_of": 32,
          "player1": {
            "id": "37b183a9-2f1a-4668-8d1b-5de5e30f5f4d",
            "name": "Player 3"
          },
          "seed1": 3,
          "player2": null,
          "seed2": null,
          "participant1_id": "30054a91-8c7b-490d-8a1a-c5729fdb3382",
          "participant1_name": "Player 3",
          "participant2_id": null,
          "participant2_name": "TBD",
          "score": null,
          "winner_id": null,
          "next_match_id": null,
          "match_iteration": 41
        },
        {
          "id": "1f98ed87-1bc7-4b20-a832-79e3b8ddfc93",
          "match_number": "32.10",
          "match_id": null,
          "round_of_text": "Round of 32",
          "round_of": 32,
          "player1": {
            "id": "730dd837-e32e-4ec5-8ad4-eaa632c8354c",
            "name": "Player 27"
          },
          "seed1": null,
          "player2": {
            "id": "9e234b21-2ff1-4d5e-bcba-65623421fbb4",
            "name": "Player 20"
          },
          "seed2": null,
          "participant1_id": "2e1249d1-9a11-42dd-a435-a45d17fb8ec6",
          "participant1_name": "Player 27",
          "participant2_id": "fb4f9084-6878-48f7-a0ef-26213023a98d",
          "participant2_name": "Player 20",
          "score": null,
          "winner_id": null,
          "next_match_id": null,
          "match_iteration": 42
        },
        {
          "id": "d9d974eb-0224-4d56-a502-d8dc25fd6f34",
          "match_number": "32.10",
          "match_id": null,
          "round_of_text": "Round of 32",
          "round_of": 32,
          "player1": {
            "id": "a9398bf4-c504-42b1-b075-75a819ff45db",
            "name": "Player 36"
          },
          "seed1": null,
          "player2": {
            "id": "4b98ecc9-f563-4728-96c3-61783d09d149",
            "name": "Player 10"
          },
          "seed2": 10,
          "participant1_id": "7e95a6c3-191d-4ad0-a38f-0b141676e2e1",
          "participant1_name": "Player 36",
          "participant2_id": "761fd629-9b28-4926-90cb-26e60813b778",
          "participant2_name": "Player 10",
          "score": null,
          "winner_id": null,
          "next_match_id": null,
          "match_iteration": 43
        },
        {
          "id": "166010f3-9c7a-43ed-bfa9-ec39e2e05a44",
          "match_number": "32.11",
          "match_id": null,
          "round_of_text": "Round of 32",
          "round_of": 32,
          "player1": {
            "id": "47da200a-ddaf-446e-b986-49991c9335d2",
            "name": "Player 32"
          },
          "seed1": null,
          "player2": {
            "id": "81e8ca43-c197-4ea6-bdc4-60eb3c57e56f",
            "name": "Player 28"
          },
          "seed2": null,
          "participant1_id": "14abf1ef-392c-4645-b856-50758eef5a94",
          "participant1_name": "Player 32",
          "participant2_id": "d7368474-215a-4c24-857b-838f861d13ae",
          "participant2_name": "Player 28",
          "score": null,
          "winner_id": null,
          "next_match_id": null,
          "match_iteration": 44
        },
        {
          "id": "0dcedd2e-2bd0-4c93-9527-7feebaee7d8a",
          "match_number": "32.13",
          "match_id": null,
          "round_of_text": "Round of 32",
          "round_of": 32,
          "player1": {
            "id": "7364e984-8e76-4a63-88fe-31f2bf7d0de8",
            "name": "Player 7"
          },
          "seed1": 7,
          "player2": {
            "id": "aac49fb5-cd1b-480d-adf7-c46a133e6d50",
            "name": "Player 6"
          },
          "seed2": 6,
          "participant1_id": "9132bb96-1796-4d4a-abf5-0da7849f0347",
          "participant1_name": "Player 7",
          "participant2_id": "ff9223fa-5fb3-4bf0-a271-16fdf89fe2ca",
          "participant2_name": "Player 6",
          "score": null,
          "winner_id": null,
          "next_match_id": null,
          "match_iteration": 45
        },
        {
          "id": "b051a857-9f2e-4437-bf78-860efa62921c",
          "match_number": "32.15",
          "match_id": null,
          "round_of_text": "Round of 32",
          "round_of": 32,
          "player1": {
            "id": "3a79c79f-2be7-4e9c-ac79-d297847c9397",
            "name": "Player 33"
          },
          "seed1": null,
          "player2": {
            "id": "15c9c434-8356-4720-9b1d-6bbb4ca4fb63",
            "name": "Player 24"
          },
          "seed2": null,
          "participant1_id": "2c552e34-709b-40bb-8060-192088c3e82e",
          "participant1_name": "Player 33",
          "participant2_id": "9bc322f6-57ac-46b1-8364-ba13de064a57",
          "participant2_name": "Player 24",
          "score": null,
          "winner_id": null,
          "next_match_id": null,
          "match_iteration": 46
        },
        {
          "id": "b0fcb45b-632c-4d7c-bf43-d3231ca1722b",
          "match_number": "32.15",
          "match_id": null,
          "round_of_text": "Round of 32",
          "round_of": 32,
          "player1": {
            "id": "ece7b417-1273-4a82-acba-b5b0ed0fbae2",
            "name": "Player 21"
          },
          "seed1": null,
          "player2": {
            "id": "2db85fa0-eeda-4bcd-8a7b-c10c08634283",
            "name": "Player 14"
          },
          "seed2": null,
          "participant1_id": "3c310670-1540-4b1d-9b62-1f5b76565ade",
          "participant1_name": "Player 21",
          "participant2_id": "5854dad8-8426-42f7-88b8-af4c20df3304",
          "participant2_name": "Player 14",
          "score": null,
          "winner_id": null,
          "next_match_id": null,
          "match_iteration": 47
        },
        {
          "id": "725477f8-d695-4c73-9d39-6c6ec84dd3f8",
          "match_number": "32.16",
          "match_id": null,
          "round_of_text": "Round of 32",
          "round_of": 32,
          "player1": {
            "id": "b1f79227-5638-4073-b4e5-9f21c7896fb2",
            "name": "Player 2"
          },
          "seed1": 2,
          "player2": null,
          "seed2": null,
          "participant1_id": "878ecee1-9dcb-436c-ac99-8ef2561b9edb",
          "participant1_name": "Player 2",
          "participant2_id": null,
          "participant2_name": "TBD",
          "score": null,
          "winner_id": null,
          "next_match_id": null,
          "match_iteration": 48
        }
      ]
    },
    {
      "round_of": 16,
      "round_of_text": "Round of 16",
      "matches": [
        {
          "id": "0c504340-e6eb-4de4-91e2-c23e26ece517",
          "match_number": "16.1",
          "match_id": null,
          "round_of_text": "Round of 16",
          "round_of": 16,
          "player1": null,
          "seed1": null,
          "player2": null,
          "seed2": null,
          "participant1_id": null,
          "participant1_name": "TBD",
          "participant2_id": null,
          "participant2_name": "TBD",
          "score": null,
          "winner_id": null,
          "next_match_id": null,
          "match_iteration": 49
        },
        {
          "id": "a0147f2a-5a5a-47dc-8690-04edf35e28b3",
          "match_number": "16.2",
          "match_id": null,
          "round_of_text": "Round of 16",
          "round_of": 16,
          "player1": null,
          "seed1": null,
          "player2": null,
          "seed2": null,
          "participant1_id": null,
          "participant1_name": "TBD",
          "participant2_id": null,
          "participant2_name": "TBD",
          "score": null,
          "winner_id": null,
          "next_match_id": null,
          "match_iteration": 50
        },
        {
          "id": "63318dee-058a-4a1c-b56c-b16f80c8d653",
          "match_number": "16.3",
          "match_id": null,
          "round_of_text": "Round of 16",
          "round_of": 16,
          "player1": null,
          "seed1": null,
          "player2": null,
          "seed2": null,
          "participant1_id": null,
          "participant1_name": "TBD",
          "participant2_id": null,
          "participant2_name": "TBD",
          "score": null,
          "winner_id": null,
          "next_match_id": null,
          "match_iteration": 51
        },
        {
          "id": "3d7d39ab-ecc8-4232-bdc3-8ea8c0a31702",
          "match_number": "16.4",
          "match_id": null,
          "round_of_text": "Round of 16",
          "round_of": 16,
          "player1": null,
          "seed1": null,
          "player2": null,
          "seed2": null,
          "participant1_id": null,
          "participant1_name": "TBD",
          "participant2_id": null,
          "participant2_name": "TBD",
          "score": null,
          "winner_id": null,
          "next_match_id": null,
          "match_iteration": 52
        },
        {
          "id": "9abac0ef-ac1b-4e5f-a39b-6fdb0e099737",
          "match_number": "16.5",
          "match_id": null,
          "round_of_text": "Round of 16",
          "round_of": 16,
          "player1": null,
          "seed1": null,
          "player2": null,
          "seed2": null,
          "participant1_id": null,
          "participant1_name": "TBD",
          "participant2_id": null,
          "participant2_name": "TBD",
          "score": null,
          "winner_id": null,
          "next_match_id": null,
          "match_iteration": 53
        },
        {
          "id": "cdcbc98c-620e-4b04-9f37-a9a2e151f383",
          "match_number": "16.6",
          "match_id": null,
          "round_of_text": "Round of 16",
          "round_of": 16,
          "player1": null,
          "seed1": null,
          "player2": null,
          "seed2": null,
          "participant1_id": null,
          "participant1_name": "TBD",
          "participant2_id": null,
          "participant2_name": "TBD",
          "score": null,
          "winner_id": null,
          "next_match_id": null,
          "match_iteration": 54
        },
        {
          "id": "49029a3e-d50e-4956-8337-e1eefc7bb638",
          "match_number": "16.7",
          "match_id": null,
          "round_of_text": "Round of 16",
          "round_of": 16,
          "player1": null,
          "seed1": null,
          "player2": null,
          "seed2": null,
          "participant1_id": null,
          "participant1_name": "TBD",
          "participant2_id": null,
          "participant2_name": "TBD",
          "score": null,
          "winner_id": null,
          "next_match_id": null,
          "match_iteration": 55
        },
        {
          "id": "948c072d-3b56-4482-bc4b-313a6d644720",
          "match_number": "16.8",
          "match_id": null,
          "round_of_text": "Round of 16",
          "round_of": 16,
          "player1": null,
          "seed1": null,
          "player2": null,
          "seed2": null,
          "participant1_id": null,
          "participant1_name": "TBD",
          "participant2_id": null,
          "participant2_name": "TBD",
          "score": null,
          "winner_id": null,
          "next_match_id": null,
          "match_iteration": 56
        }
      ]
    },
    {
      "round_of": 8,
      "round_of_text": "Quarterfinals",
      "matches": [
        {
          "id": "65a98abd-e3c3-4620-8eda-7e8977ce88a3",
          "match_number": "8.1",
          "match_id": null,
          "round_of_text": "Quarterfinals",
          "round_of": 8,
          "player1": null,
          "seed1": null,
          "player2": null,
          "seed2": null,
          "participant1_id": null,
          "participant1_name": "TBD",
          "participant2_id": null,
          "participant2_name": "TBD",
          "score": null,
          "winner_id": null,
          "next_match_id": null,
          "match_iteration": 57
        },
        {
          "id": "161f47da-dc92-48c0-8d21-358434d07318",
          "match_number": "8.2",
          "match_id": null,
          "round_of_text": "Quarterfinals",
          "round_of": 8,
          "player1": null,
          "seed1": null,
          "player2": null,
          "seed2": null,
          "participant1_id": null,
          "participant1_name": "TBD",
          "participant2_id": null,
          "participant2_name": "TBD",
          "score": null,
          "winner_id": null,
          "next_match_id": null,
          "match_iteration": 58
        },
        {
          "id": "68d46e87-2daf-4f49-a149-68cab593dba3",
          "match_number": "8.3",
          "match_id": null,
          "round_of_text": "Quarterfinals",
          "round_of": 8,
          "player1": null,
          "seed1": null,
          "player2": null,
          "seed2": null,
          "participant1_id": null,
          "participant1_name": "TBD",
          "participant2_id": null,
          "participant2_name": "TBD",
          "score": null,
          "winner_id": null,
          "next_match_id": null,
          "match_iteration": 59
        },
        {
          "id": "3ef0c563-694f-4363-a5f1-e66b56ae2219",
          "match_number": "8.4",
          "match_id": null,
          "round_of_text": "Quarterfinals",
          "round_of": 8,
          "player1": null,
          "seed1": null,
          "player2": null,
          "seed2": null,
          "participant1_id": null,
          "participant1_name": "TBD",
          "participant2_id": null,
          "participant2_name": "TBD",
          "score": null,
          "winner_id": null,
          "next_match_id": null,
          "match_iteration": 60
        }
      ]
    },
    {
      "round_of": 4,
      "round_of_text": "Semifinals",
      "matches": [
        {
          "id": "8d2f477e-8a3c-4233-9eeb-db8c0740e02b",
          "match_number": "4.1",
          "match_id": null,
          "round_of_text": "Semifinals",
          "round_of": 4,
          "player1": null,
          "seed1": null,
          "player2": null,
          "seed2": null,
          "participant1_id": null,
          "participant1_name": "TBD",
          "participant2_id": null,
          "participant2_name": "TBD",
          "score": null,
          "winner_id": null,
          "next_match_id": null,
          "match_iteration": 61
        },
        {
          "id": "9fe26e11-ee98-47fa-a45c-93c12cd1c8cb",
          "match_number": "4.2",
          "match_id": null,
          "round_of_text": "Semifinals",
          "round_of": 4,
          "player1": null,
          "seed1": null,
          "player2": null,
          "seed2": null,
          "participant1_id": null,
          "participant1_name": "TBD",
          "participant2_id": null,
          "participant2_name": "TBD",
          "score": null,
          "winner_id": null,
          "next_match_id": null,
          "match_iteration": 62
        }
      ]
    },
    {
      "round_of": 2,
      "round_of_text": "Final",
      "matches": [
        {
          "id": "3bc36659-22b7-4ce7-872d-45ef2982bec1",
          "match_number": "2.1",
          "match_id": null,
          "round_of_text": "Final",
          "round_of": 2,
          "player1": null,
          "seed1": null,
          "player2": null,
          "seed2": null,
          "participant1_id": null,
          "participant1_name": "TBD",
          "participant2_id": null,
          "participant2_name": "TBD",
          "score": null,
          "winner_id": null,
          "next_match_id": null,
          "match_iteration": 63
        }
      ]
    }
  ]
}

  export default bracket_data;